### ISSUE TITLE
Download link 

### ISSUE THREAD

**Issue by HalfBloodprinc3** [rodrigmatrix/weather-you#3]
It's not available in play store. Where is the file?

**Comment by Mennaruuk** [comment]
Correct. It's no longer on the Play Store.

I did find that [APKPure has saved a copy of the APK.](https://d.apkpure.com/b/APK/com.rodrigmatrix.weatheryou?version=latest)

**Comment by HalfBloodprinc3** [comment]
> Correct. It's no longer on the Play Store.
> 
> I did find that [APKPure has saved a copy of the APK.](https://d.apkpure.com/b/APK/com.rodrigmatrix.weatheryou?version=latest) But the app is no longer functional.

Thanks buddy ❤️

**Comment by TeaOwO** [comment]
Same, I think it got removed from the playstore

**Comment by rodrigmatrix** [comment]
App fixed with version 2.1.1 on play store
